In [6]:
import torch

tensor1 = torch.rand(size=(7,7))
tensor2 = torch.rand(size=(1,7))
tensor1, tensor2

(tensor([[0.1261, 0.8621, 0.2061, 0.6592, 0.5831, 0.7387, 0.2310],
         [0.6020, 0.4371, 0.0407, 0.7694, 0.3309, 0.0664, 0.2824],
         [0.4390, 0.4717, 0.2816, 0.1661, 0.1760, 0.2280, 0.1508],
         [0.6054, 0.3046, 0.6006, 0.2771, 0.9851, 0.4663, 0.2570],
         [0.5737, 0.2087, 0.9890, 0.5503, 0.5328, 0.9641, 0.0348],
         [0.4559, 0.4341, 0.7186, 0.6524, 0.2957, 0.0235, 0.8893],
         [0.8406, 0.5707, 0.8456, 0.4543, 0.2056, 0.2489, 0.4208]]),
 tensor([[0.5461, 0.8601, 0.7404, 0.3151, 0.9971, 0.3334, 0.6622]]))

In [7]:
matrix_mul = tensor1 @ tensor2.T
matrix_mul

tensor([[2.1513],
        [1.5163],
        [1.2576],
        [2.4325],
        [2.2741],
        [2.2515],
        [2.2858]])

In [9]:
torch.manual_seed(0)
tensor1 = torch.rand(size=(7,7))
tensor2 = torch.rand(size=(1, 7))

matrix_mul = tensor1 @ tensor2.T
matrix_mul

tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]])

In [13]:
torch.manual_seed(1234)
device = "cuda"

tensor1 = torch.rand(size=(2,3)).to(device)
tensor2 = torch.rand(size=(2,3)).to(device)

tensor1, tensor2

(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))

In [15]:
matrix_mul = tensor1 @ tensor2.T
matrix_mul

tensor([[0.3647, 0.4709],
        [0.5184, 0.5617]], device='cuda:0')

In [ ]:
print(f"Max of tensor1: {tensor1.max():.2f}")
print(f"Max of tensor2: {tensor2.max():.2f}")

print(f"Min of tensor1: {tensor1.min():.2f}")
print(f"Min of tensor2: {tensor2.min():.2f}")

Max of tensor1: 0.70
Max of tensor2: 0.78


In [20]:
print(f"Index of tensor1's max: {tensor1.argmax()}")
print(f"Index of tensor2's max: {tensor2.argmax()}")

print(f"Index of tensor1's min: {tensor1.argmin()}")
print(f"Index of tensor2's min: {tensor2.argmin()}")

Index of tensor1's max: 5
Index of tensor2's max: 4
Index of tensor1's min: 0
Index of tensor2's min: 0


In [21]:
tensor = torch.rand(size=(1, 1, 1, 10))
tensor

tensor([[[[0.7749, 0.8208, 0.2793, 0.6817, 0.2837, 0.6567, 0.2388, 0.7313,
           0.6012, 0.3043]]]])

In [22]:
tensor.reshape(10)

tensor([0.7749, 0.8208, 0.2793, 0.6817, 0.2837, 0.6567, 0.2388, 0.7313, 0.6012,
        0.3043])