In [64]:
import torch
import numpy as np

torch.cuda.is_available()

False

In [18]:
# Scalar: 0 dimensional tensor
scalar = torch.tensor(7)
scalar.shape

torch.Size([])

In [19]:
# Matrix: 2 dimensional tensor
matrix = torch.tensor([[7, 7], [7, 7]])
matrix.shape

torch.Size([2, 2])

In [20]:
# Tensor: n dimensional tensor
tensor = torch.tensor([[[7, 7, 7], [7, 7, 7], [7, 7, 7]]])
tensor.shape

torch.Size([1, 3, 3])

In [21]:
random_tensor = torch.rand(size=(3, 4))
random_tensor

tensor([[0.2852, 0.8181, 0.5617, 0.1899],
        [0.6233, 0.4440, 0.8140, 0.9103],
        [0.4170, 0.9812, 0.9185, 0.9740]])

In [22]:
zeros = torch.zeros(size=(3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [23]:
ones = torch.ones(size=(3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [24]:
zero_to_ten = torch.arange(start=0, end=10, step=1)
zero_to_ten

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
ten_zeros = torch.zeros_like(input=zero_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [26]:
float_32_tensor = torch.tensor([3.0, 6.0, 9.0], dtype=torch.float32)
float_32_tensor.device

device(type='cpu')

In [34]:
tensor = torch.tensor([1, 2, 3])
print(tensor + 10)
print(tensor.add(10))

tensor([11, 12, 13])
tensor([11, 12, 13])


In [35]:
print(tensor * 10)
print(tensor.mul(10))

tensor([10, 20, 30])
tensor([10, 20, 30])


In [36]:
tensor = tensor - 10
tensor

tensor([-9, -8, -7])

In [43]:
tensor1 = torch.tensor([1, 2, 3])
tensor2 = torch.tensor([4, 5, 6])

matrix_mult = torch.matmul(tensor1, tensor2)
print(matrix_mult)
print(tensor1 @ tensor2)

# tensor1 * tensor2 is element-wise multiplication
element_wise_mult = tensor1 * tensor2
print(element_wise_mult)

tensor(32)
tensor(32)
tensor([ 4, 10, 18])


In [46]:
x = torch.arange(0, 100, 10, dtype=float)
print(x)
print(f"Maximum: {x.max()}")
print(f"Minimum: {x.min()}")
print(f"Mean: {x.mean()}") # Wothout dtype float, it doesn't work
print(f"Sum: {x.sum()}")

tensor([ 0., 10., 20., 30., 40., 50., 60., 70., 80., 90.], dtype=torch.float64)
Maximum: 90.0
Minimum: 0.0
Mean: 45.0
Sum: 450.0


In [47]:
print(f"Position of max: {x.argmax()}")
print(f"Position of min: {x.argmin()}")

Position of max: 9
Position of min: 0


In [51]:
print(x.dtype)
tensor_int32 = x.type(torch.int32)
print(tensor_int32.dtype)

torch.float64
torch.int32


In [ ]:
array = np.arange(1.0, 10.0)
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7., 8., 9.]),
 tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=torch.float64))

In [56]:
tensor.numpy()

array([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [1]:
!nvidia-smi

Wed Nov 26 14:13:58 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 581.80                 Driver Version: 581.80         CUDA Version: 13.0     |
+-----------------------------------------+------------------------+----------------------+
| GPU  Name                  Driver-Model | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce RTX 3060      WDDM  |   00000000:0B:00.0  On |                  N/A |
|  0%   42C    P8             20W /  170W |    1761MiB /  12288MiB |     23%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----